#!/usr/bin/env python3
"""Regrid the 68-band CARMA haze optics files to the 84-band (n84/exort) grid.

The n84 spectral grid is a strict superset of the n68 grid: bands 1..68 have
identical edges, and bands 69..84 add UV coverage above 42,087 cm-1 (below
~0.238 um). This tool therefore copies the 68 in-range bands *verbatim* from
the validated haze_n68_b40_*.nc tables and fills the 16 new UV bands by
extending the highest-wavenumber n68 band (band 68, 0.238-0.26 um).

*** The UV extension is PROVISIONAL. *** Tholin extinction generally keeps
rising and darkening into the UV, so nearest-band extension underestimates UV
opacity. The output files are stamped with a `provisional` global attribute and
should be replaced by a proper Mie/fractal recomputation from the refractive
indices in data/aerosol/refractive_indices/ when the 84-band haze optics are
regenerated offline. Bands 1..68 in the output are exact copies and will not
change unless the source tables do.

Usage (from anywhere; paths are repo-relative to this file):
    python tools/regrid_haze_optics.py             # both mie and fractal_interp
    python tools/regrid_haze_optics.py --which mie
"""
import argparse
import datetime
import os
import sys

import numpy as np
import netCDF4 as nc

HERE = os.path.dirname(os.path.abspath(__file__))
AERDIR = os.path.join(HERE, "..", "data", "aerosol")

sys.path.insert(0, HERE)
from spectral_intervals import wavenum_edge_n68, wavenum_edge_n84  # noqa: E402

N68 = 68
N84 = 84
OPTICS_VARS = ("Qext", "Kext", "W", "G")   # dimensioned (nwavlrng, nbins, nelements)


def regrid_file(tag):
    src_path = os.path.join(AERDIR, f"haze_n68_b40_{tag}.nc")
    out_path = os.path.join(AERDIR, f"haze_n84_b40_{tag}.nc")

    e68 = np.asarray(wavenum_edge_n68, dtype="f8")
    e84 = np.asarray(wavenum_edge_n84, dtype="f8")
    assert np.allclose(e84[: N68 + 1], e68), "n68 edges are not a prefix of n84"

    with nc.Dataset(src_path) as src:
        wsrc = src.variables["wvnrng"][:]
        if not np.allclose(np.asarray(wsrc, dtype="f8"), e68, rtol=1e-5):
            sys.exit(f"ERROR: {src_path} wvnrng does not match the n68 grid")
        nbins = len(src.dimensions["nbins"])
        nelem = len(src.dimensions["nelements"])

        with nc.Dataset(out_path, "w") as out:
            out.createDimension("nelements", nelem)
            out.createDimension("nbins", nbins)
            out.createDimension("nwavlrng", N84)
            out.createDimension("nwave_edge", N84 + 1)

            def clone(name, dims, data):
                v_src = src.variables[name]
                v = out.createVariable(name, v_src.dtype, dims)
                for att in v_src.ncattrs():
                    v.setncattr(att, v_src.getncattr(att))
                v[:] = data

            clone("rmrat", ("nelements",), src.variables["rmrat"][:])
            clone("rbins", ("nbins", "nelements"), src.variables["rbins"][:])

            v = out.createVariable("wvnrng", "f4", ("nwave_edge",))
            v.title = "wavenumber at edges"
            v.units = "cm-1"
            v[:] = e84

            for name in OPTICS_VARS:
                data68 = src.variables[name][:]          # (68, nbins, nelem)
                data84 = np.empty((N84,) + data68.shape[1:], dtype=data68.dtype)
                data84[:N68] = data68
                data84[N68:] = data68[N68 - 1]           # UV bands: extend band 68
                clone_dims = ("nwavlrng", "nbins", "nelements")
                v_src = src.variables[name]
                v = out.createVariable(name, v_src.dtype, clone_dims)
                for att in v_src.ncattrs():
                    v.setncattr(att, v_src.getncattr(att))
                v[:] = data84

            out.source_file = os.path.basename(src_path)
            out.provisional = (
                "Bands 1-68 copied verbatim from the n68 table (identical band "
                "edges). Bands 69-84 (UV, >42087 cm-1) are a nearest-band "
                "extension of band 68 and are PROVISIONAL; replace with a "
                "proper 84-band optics recomputation."
            )
            out.history = (
                f"{datetime.date.today().isoformat()}: generated by "
                "tools/regrid_haze_optics.py"
            )

    print(f"wrote {out_path}")


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--which", choices=("mie", "fractal_interp", "both"),
                   default="both")
    args = p.parse_args()
    tags = ("mie", "fractal_interp") if args.which == "both" else (args.which,)
    for tag in tags:
        regrid_file(tag)


if __name__ == "__main__":
    main()
